// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo3.common.protobuf;

public final class Communication {
  private Communication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TranslationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TranslationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DictionaryServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DictionaryServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TranslationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TranslationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Communication.proto\"\\\n\022TranslationRequ" +
      "est\022\023\n\013source_word\030\001 \001(\t\022\034\n\024translation_" +
      "language\030\002 \001(\t\022\023\n\013client_port\030\003 \001(\r\"[\n\027D" +
      "ictionaryServerRequest\022\023\n\013source_word\030\001 " +
      "\001(\t\022\026\n\016client_address\030\002 \001(\t\022\023\n\013client_po" +
      "rt\030\003 \001(\r\"z\n\023TranslationResponse\022\027\n\006statu" +
      "s\030\001 \001(\0162\007.Status\022\023\n\013source_word\030\002 \001(\t\022\027\n" +
      "\017translated_word\030\003 \001(\t\022\034\n\024translation_la" +
      "nguage\030\004 \001(\t\"\222\001\n\023RegistrationRequest\022.\n\004" +
      "type\030\001 \001(\0162 .RegistrationRequest.Request" +
      "Type\022\014\n\004port\030\003 \001(\r\022\020\n\010language\030\004 \001(\t\"+\n\013" +
      "RequestType\022\014\n\010REGISTER\020\000\022\016\n\nUNREGISTER\020" +
      "\001\"#\n\010Response\022\027\n\006status\030\001 \001(\0162\007.Status*=" +
      "\n\006Status\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001\022\021\n\rNOT_SUPPO" +
      "RTED\020\002\022\r\n\tNOT_FOUND\020\003B\"\n\036com.mdevv.tpo3." +
      "common.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TranslationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TranslationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TranslationRequest_descriptor,
        new java.lang.String[] { "SourceWord", "TranslationLanguage", "ClientPort", });
    internal_static_DictionaryServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DictionaryServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DictionaryServerRequest_descriptor,
        new java.lang.String[] { "SourceWord", "ClientAddress", "ClientPort", });
    internal_static_TranslationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TranslationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TranslationResponse_descriptor,
        new java.lang.String[] { "Status", "SourceWord", "TranslatedWord", "TranslationLanguage", });
    internal_static_RegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationRequest_descriptor,
        new java.lang.String[] { "Type", "Port", "Language", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
