// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo3.common.protobuf;

public interface DictionaryServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DictionaryServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source_word = 1;</code>
   * @return The sourceWord.
   */
  java.lang.String getSourceWord();
  /**
   * <code>string source_word = 1;</code>
   * @return The bytes for sourceWord.
   */
  com.google.protobuf.ByteString
      getSourceWordBytes();

  /**
   * <code>string client_address = 2;</code>
   * @return The clientAddress.
   */
  java.lang.String getClientAddress();
  /**
   * <code>string client_address = 2;</code>
   * @return The bytes for clientAddress.
   */
  com.google.protobuf.ByteString
      getClientAddressBytes();

  /**
   * <code>uint32 client_port = 3;</code>
   * @return The clientPort.
   */
  int getClientPort();
}
