// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo3.common.protobuf;

public interface RegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RegistrationRequest.RequestType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.RegistrationRequest.RequestType type = 1;</code>
   * @return The type.
   */
  com.mdevv.tpo3.common.protobuf.RegistrationRequest.RequestType getType();

  /**
   * <code>uint32 port = 3;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>string language = 4;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 4;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();
}
