// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo3.common.protobuf;

/**
 * <pre>
 * From client to core server
 * </pre>
 *
 * Protobuf type {@code TranslationRequest}
 */
public  final class TranslationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TranslationRequest)
    TranslationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TranslationRequest.newBuilder() to construct.
  private TranslationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TranslationRequest() {
    sourceWord_ = "";
    translationLanguage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TranslationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TranslationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceWord_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            translationLanguage_ = s;
            break;
          }
          case 24: {

            clientPort_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdevv.tpo3.common.protobuf.TranslationRequest.class, com.mdevv.tpo3.common.protobuf.TranslationRequest.Builder.class);
  }

  public static final int SOURCE_WORD_FIELD_NUMBER = 1;
  private volatile java.lang.Object sourceWord_;
  /**
   * <code>string source_word = 1;</code>
   * @return The sourceWord.
   */
  public java.lang.String getSourceWord() {
    java.lang.Object ref = sourceWord_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceWord_ = s;
      return s;
    }
  }
  /**
   * <code>string source_word = 1;</code>
   * @return The bytes for sourceWord.
   */
  public com.google.protobuf.ByteString
      getSourceWordBytes() {
    java.lang.Object ref = sourceWord_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceWord_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSLATION_LANGUAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object translationLanguage_;
  /**
   * <code>string translation_language = 2;</code>
   * @return The translationLanguage.
   */
  public java.lang.String getTranslationLanguage() {
    java.lang.Object ref = translationLanguage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      translationLanguage_ = s;
      return s;
    }
  }
  /**
   * <code>string translation_language = 2;</code>
   * @return The bytes for translationLanguage.
   */
  public com.google.protobuf.ByteString
      getTranslationLanguageBytes() {
    java.lang.Object ref = translationLanguage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      translationLanguage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_PORT_FIELD_NUMBER = 3;
  private int clientPort_;
  /**
   * <code>uint32 client_port = 3;</code>
   * @return The clientPort.
   */
  public int getClientPort() {
    return clientPort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSourceWordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceWord_);
    }
    if (!getTranslationLanguageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, translationLanguage_);
    }
    if (clientPort_ != 0) {
      output.writeUInt32(3, clientPort_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSourceWordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceWord_);
    }
    if (!getTranslationLanguageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, translationLanguage_);
    }
    if (clientPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, clientPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdevv.tpo3.common.protobuf.TranslationRequest)) {
      return super.equals(obj);
    }
    com.mdevv.tpo3.common.protobuf.TranslationRequest other = (com.mdevv.tpo3.common.protobuf.TranslationRequest) obj;

    if (!getSourceWord()
        .equals(other.getSourceWord())) return false;
    if (!getTranslationLanguage()
        .equals(other.getTranslationLanguage())) return false;
    if (getClientPort()
        != other.getClientPort()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_WORD_FIELD_NUMBER;
    hash = (53 * hash) + getSourceWord().hashCode();
    hash = (37 * hash) + TRANSLATION_LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getTranslationLanguage().hashCode();
    hash = (37 * hash) + CLIENT_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getClientPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdevv.tpo3.common.protobuf.TranslationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * From client to core server
   * </pre>
   *
   * Protobuf type {@code TranslationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TranslationRequest)
      com.mdevv.tpo3.common.protobuf.TranslationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdevv.tpo3.common.protobuf.TranslationRequest.class, com.mdevv.tpo3.common.protobuf.TranslationRequest.Builder.class);
    }

    // Construct using com.mdevv.tpo3.common.protobuf.TranslationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sourceWord_ = "";

      translationLanguage_ = "";

      clientPort_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationRequest_descriptor;
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationRequest getDefaultInstanceForType() {
      return com.mdevv.tpo3.common.protobuf.TranslationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationRequest build() {
      com.mdevv.tpo3.common.protobuf.TranslationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationRequest buildPartial() {
      com.mdevv.tpo3.common.protobuf.TranslationRequest result = new com.mdevv.tpo3.common.protobuf.TranslationRequest(this);
      result.sourceWord_ = sourceWord_;
      result.translationLanguage_ = translationLanguage_;
      result.clientPort_ = clientPort_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdevv.tpo3.common.protobuf.TranslationRequest) {
        return mergeFrom((com.mdevv.tpo3.common.protobuf.TranslationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdevv.tpo3.common.protobuf.TranslationRequest other) {
      if (other == com.mdevv.tpo3.common.protobuf.TranslationRequest.getDefaultInstance()) return this;
      if (!other.getSourceWord().isEmpty()) {
        sourceWord_ = other.sourceWord_;
        onChanged();
      }
      if (!other.getTranslationLanguage().isEmpty()) {
        translationLanguage_ = other.translationLanguage_;
        onChanged();
      }
      if (other.getClientPort() != 0) {
        setClientPort(other.getClientPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mdevv.tpo3.common.protobuf.TranslationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mdevv.tpo3.common.protobuf.TranslationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sourceWord_ = "";
    /**
     * <code>string source_word = 1;</code>
     * @return The sourceWord.
     */
    public java.lang.String getSourceWord() {
      java.lang.Object ref = sourceWord_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceWord_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_word = 1;</code>
     * @return The bytes for sourceWord.
     */
    public com.google.protobuf.ByteString
        getSourceWordBytes() {
      java.lang.Object ref = sourceWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_word = 1;</code>
     * @param value The sourceWord to set.
     * @return This builder for chaining.
     */
    public Builder setSourceWord(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceWord_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source_word = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceWord() {
      
      sourceWord_ = getDefaultInstance().getSourceWord();
      onChanged();
      return this;
    }
    /**
     * <code>string source_word = 1;</code>
     * @param value The bytes for sourceWord to set.
     * @return This builder for chaining.
     */
    public Builder setSourceWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceWord_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object translationLanguage_ = "";
    /**
     * <code>string translation_language = 2;</code>
     * @return The translationLanguage.
     */
    public java.lang.String getTranslationLanguage() {
      java.lang.Object ref = translationLanguage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        translationLanguage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string translation_language = 2;</code>
     * @return The bytes for translationLanguage.
     */
    public com.google.protobuf.ByteString
        getTranslationLanguageBytes() {
      java.lang.Object ref = translationLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        translationLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string translation_language = 2;</code>
     * @param value The translationLanguage to set.
     * @return This builder for chaining.
     */
    public Builder setTranslationLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      translationLanguage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string translation_language = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranslationLanguage() {
      
      translationLanguage_ = getDefaultInstance().getTranslationLanguage();
      onChanged();
      return this;
    }
    /**
     * <code>string translation_language = 2;</code>
     * @param value The bytes for translationLanguage to set.
     * @return This builder for chaining.
     */
    public Builder setTranslationLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      translationLanguage_ = value;
      onChanged();
      return this;
    }

    private int clientPort_ ;
    /**
     * <code>uint32 client_port = 3;</code>
     * @return The clientPort.
     */
    public int getClientPort() {
      return clientPort_;
    }
    /**
     * <code>uint32 client_port = 3;</code>
     * @param value The clientPort to set.
     * @return This builder for chaining.
     */
    public Builder setClientPort(int value) {
      
      clientPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 client_port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientPort() {
      
      clientPort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TranslationRequest)
  }

  // @@protoc_insertion_point(class_scope:TranslationRequest)
  private static final com.mdevv.tpo3.common.protobuf.TranslationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdevv.tpo3.common.protobuf.TranslationRequest();
  }

  public static com.mdevv.tpo3.common.protobuf.TranslationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TranslationRequest>
      PARSER = new com.google.protobuf.AbstractParser<TranslationRequest>() {
    @java.lang.Override
    public TranslationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TranslationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TranslationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TranslationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdevv.tpo3.common.protobuf.TranslationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

