// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo3.common.protobuf;

/**
 * <pre>
 * From dict server to client
 * </pre>
 *
 * Protobuf type {@code TranslationResponse}
 */
public  final class TranslationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TranslationResponse)
    TranslationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TranslationResponse.newBuilder() to construct.
  private TranslationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TranslationResponse() {
    status_ = 0;
    sourceWord_ = "";
    translatedWord_ = "";
    translationLanguage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TranslationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TranslationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceWord_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            translatedWord_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            translationLanguage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdevv.tpo3.common.protobuf.TranslationResponse.class, com.mdevv.tpo3.common.protobuf.TranslationResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.Status status = 1;</code>
   * @return The status.
   */
  public com.mdevv.tpo3.common.protobuf.Status getStatus() {
    @SuppressWarnings("deprecation")
    com.mdevv.tpo3.common.protobuf.Status result = com.mdevv.tpo3.common.protobuf.Status.valueOf(status_);
    return result == null ? com.mdevv.tpo3.common.protobuf.Status.UNRECOGNIZED : result;
  }

  public static final int SOURCE_WORD_FIELD_NUMBER = 2;
  private volatile java.lang.Object sourceWord_;
  /**
   * <code>string source_word = 2;</code>
   * @return The sourceWord.
   */
  public java.lang.String getSourceWord() {
    java.lang.Object ref = sourceWord_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceWord_ = s;
      return s;
    }
  }
  /**
   * <code>string source_word = 2;</code>
   * @return The bytes for sourceWord.
   */
  public com.google.protobuf.ByteString
      getSourceWordBytes() {
    java.lang.Object ref = sourceWord_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceWord_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSLATED_WORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object translatedWord_;
  /**
   * <code>string translated_word = 3;</code>
   * @return The translatedWord.
   */
  public java.lang.String getTranslatedWord() {
    java.lang.Object ref = translatedWord_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      translatedWord_ = s;
      return s;
    }
  }
  /**
   * <code>string translated_word = 3;</code>
   * @return The bytes for translatedWord.
   */
  public com.google.protobuf.ByteString
      getTranslatedWordBytes() {
    java.lang.Object ref = translatedWord_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      translatedWord_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSLATION_LANGUAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object translationLanguage_;
  /**
   * <code>string translation_language = 4;</code>
   * @return The translationLanguage.
   */
  public java.lang.String getTranslationLanguage() {
    java.lang.Object ref = translationLanguage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      translationLanguage_ = s;
      return s;
    }
  }
  /**
   * <code>string translation_language = 4;</code>
   * @return The bytes for translationLanguage.
   */
  public com.google.protobuf.ByteString
      getTranslationLanguageBytes() {
    java.lang.Object ref = translationLanguage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      translationLanguage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.mdevv.tpo3.common.protobuf.Status.OK.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (!getSourceWordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceWord_);
    }
    if (!getTranslatedWordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, translatedWord_);
    }
    if (!getTranslationLanguageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, translationLanguage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.mdevv.tpo3.common.protobuf.Status.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (!getSourceWordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceWord_);
    }
    if (!getTranslatedWordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, translatedWord_);
    }
    if (!getTranslationLanguageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, translationLanguage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdevv.tpo3.common.protobuf.TranslationResponse)) {
      return super.equals(obj);
    }
    com.mdevv.tpo3.common.protobuf.TranslationResponse other = (com.mdevv.tpo3.common.protobuf.TranslationResponse) obj;

    if (status_ != other.status_) return false;
    if (!getSourceWord()
        .equals(other.getSourceWord())) return false;
    if (!getTranslatedWord()
        .equals(other.getTranslatedWord())) return false;
    if (!getTranslationLanguage()
        .equals(other.getTranslationLanguage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + SOURCE_WORD_FIELD_NUMBER;
    hash = (53 * hash) + getSourceWord().hashCode();
    hash = (37 * hash) + TRANSLATED_WORD_FIELD_NUMBER;
    hash = (53 * hash) + getTranslatedWord().hashCode();
    hash = (37 * hash) + TRANSLATION_LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getTranslationLanguage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdevv.tpo3.common.protobuf.TranslationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdevv.tpo3.common.protobuf.TranslationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * From dict server to client
   * </pre>
   *
   * Protobuf type {@code TranslationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TranslationResponse)
      com.mdevv.tpo3.common.protobuf.TranslationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdevv.tpo3.common.protobuf.TranslationResponse.class, com.mdevv.tpo3.common.protobuf.TranslationResponse.Builder.class);
    }

    // Construct using com.mdevv.tpo3.common.protobuf.TranslationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      sourceWord_ = "";

      translatedWord_ = "";

      translationLanguage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdevv.tpo3.common.protobuf.Communication.internal_static_TranslationResponse_descriptor;
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationResponse getDefaultInstanceForType() {
      return com.mdevv.tpo3.common.protobuf.TranslationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationResponse build() {
      com.mdevv.tpo3.common.protobuf.TranslationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdevv.tpo3.common.protobuf.TranslationResponse buildPartial() {
      com.mdevv.tpo3.common.protobuf.TranslationResponse result = new com.mdevv.tpo3.common.protobuf.TranslationResponse(this);
      result.status_ = status_;
      result.sourceWord_ = sourceWord_;
      result.translatedWord_ = translatedWord_;
      result.translationLanguage_ = translationLanguage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdevv.tpo3.common.protobuf.TranslationResponse) {
        return mergeFrom((com.mdevv.tpo3.common.protobuf.TranslationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdevv.tpo3.common.protobuf.TranslationResponse other) {
      if (other == com.mdevv.tpo3.common.protobuf.TranslationResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getSourceWord().isEmpty()) {
        sourceWord_ = other.sourceWord_;
        onChanged();
      }
      if (!other.getTranslatedWord().isEmpty()) {
        translatedWord_ = other.translatedWord_;
        onChanged();
      }
      if (!other.getTranslationLanguage().isEmpty()) {
        translationLanguage_ = other.translationLanguage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mdevv.tpo3.common.protobuf.TranslationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mdevv.tpo3.common.protobuf.TranslationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Status status = 1;</code>
     * @return The status.
     */
    public com.mdevv.tpo3.common.protobuf.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.mdevv.tpo3.common.protobuf.Status result = com.mdevv.tpo3.common.protobuf.Status.valueOf(status_);
      return result == null ? com.mdevv.tpo3.common.protobuf.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.mdevv.tpo3.common.protobuf.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Status status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sourceWord_ = "";
    /**
     * <code>string source_word = 2;</code>
     * @return The sourceWord.
     */
    public java.lang.String getSourceWord() {
      java.lang.Object ref = sourceWord_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceWord_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_word = 2;</code>
     * @return The bytes for sourceWord.
     */
    public com.google.protobuf.ByteString
        getSourceWordBytes() {
      java.lang.Object ref = sourceWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_word = 2;</code>
     * @param value The sourceWord to set.
     * @return This builder for chaining.
     */
    public Builder setSourceWord(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceWord_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source_word = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceWord() {
      
      sourceWord_ = getDefaultInstance().getSourceWord();
      onChanged();
      return this;
    }
    /**
     * <code>string source_word = 2;</code>
     * @param value The bytes for sourceWord to set.
     * @return This builder for chaining.
     */
    public Builder setSourceWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceWord_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object translatedWord_ = "";
    /**
     * <code>string translated_word = 3;</code>
     * @return The translatedWord.
     */
    public java.lang.String getTranslatedWord() {
      java.lang.Object ref = translatedWord_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        translatedWord_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string translated_word = 3;</code>
     * @return The bytes for translatedWord.
     */
    public com.google.protobuf.ByteString
        getTranslatedWordBytes() {
      java.lang.Object ref = translatedWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        translatedWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string translated_word = 3;</code>
     * @param value The translatedWord to set.
     * @return This builder for chaining.
     */
    public Builder setTranslatedWord(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      translatedWord_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string translated_word = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranslatedWord() {
      
      translatedWord_ = getDefaultInstance().getTranslatedWord();
      onChanged();
      return this;
    }
    /**
     * <code>string translated_word = 3;</code>
     * @param value The bytes for translatedWord to set.
     * @return This builder for chaining.
     */
    public Builder setTranslatedWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      translatedWord_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object translationLanguage_ = "";
    /**
     * <code>string translation_language = 4;</code>
     * @return The translationLanguage.
     */
    public java.lang.String getTranslationLanguage() {
      java.lang.Object ref = translationLanguage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        translationLanguage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string translation_language = 4;</code>
     * @return The bytes for translationLanguage.
     */
    public com.google.protobuf.ByteString
        getTranslationLanguageBytes() {
      java.lang.Object ref = translationLanguage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        translationLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string translation_language = 4;</code>
     * @param value The translationLanguage to set.
     * @return This builder for chaining.
     */
    public Builder setTranslationLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      translationLanguage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string translation_language = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranslationLanguage() {
      
      translationLanguage_ = getDefaultInstance().getTranslationLanguage();
      onChanged();
      return this;
    }
    /**
     * <code>string translation_language = 4;</code>
     * @param value The bytes for translationLanguage to set.
     * @return This builder for chaining.
     */
    public Builder setTranslationLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      translationLanguage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TranslationResponse)
  }

  // @@protoc_insertion_point(class_scope:TranslationResponse)
  private static final com.mdevv.tpo3.common.protobuf.TranslationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdevv.tpo3.common.protobuf.TranslationResponse();
  }

  public static com.mdevv.tpo3.common.protobuf.TranslationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TranslationResponse>
      PARSER = new com.google.protobuf.AbstractParser<TranslationResponse>() {
    @java.lang.Override
    public TranslationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TranslationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TranslationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TranslationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdevv.tpo3.common.protobuf.TranslationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

